services:
  postgres:
    image: postgres:16
    container_name: zapiski-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strong_new_password_here
      POSTGRES_DB: Zapisi.Pro
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: zapiski-bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: strong_new_password_here
      MINIAPP_URL: https://app-zapisi-pro.site
      ASPNETCORE_URLS: http://+:8080
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      YooKassa__ShopId: ${YooKassa__ShopId}
      YooKassa__SecretKey: ${YooKassa__SecretKey}
    expose:
      - "8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_URL: https://api.app-zapisi-pro.site
    container_name: zapiski-web
    restart: unless-stopped
    depends_on:
      - bot
    ports:
      - "80:80"

volumes:
  postgres_data: